export const storeInfo = {
  name: 'SISTER TELESYSTEM',
  tagline: 'Your Trusted Mobile Store',
  description: 'Discover the latest smartphones, accessories, and expert services at SISTER TELESYSTEM. We bring you quality products and exceptional customer service.',
};

export const sampleProducts = [
  {
    id: BigInt(1),
    name: 'iPhone 15 Pro',
    brand: 'Apple',
    category: 'Smartphones',
    price: BigInt(134999),
    imageUrl: null,
    description: 'Latest flagship with A17 Pro chip and titanium design',
  },
  {
    id: BigInt(2),
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'Smartphones',
    price: BigInt(129999),
    imageUrl: null,
    description: 'Premium Android phone with S Pen and 200MP camera',
  },
  {
    id: BigInt(3),
    name: 'Google Pixel 8 Pro',
    brand: 'Google',
    category: 'Smartphones',
    price: BigInt(106999),
    imageUrl: null,
    description: 'Pure Android experience with AI-powered features',
  },
  {
    id: BigInt(4),
    name: 'OnePlus 12',
    brand: 'OnePlus',
    category: 'Smartphones',
    price: BigInt(64999),
    imageUrl: null,
    description: 'Flagship killer with Snapdragon 8 Gen 3',
  },
  {
    id: BigInt(5),
    name: 'AirPods Pro (2nd Gen)',
    brand: 'Apple',
    category: 'Accessories',
    price: BigInt(26900),
    imageUrl: null,
    description: 'Premium wireless earbuds with active noise cancellation',
  },
  {
    id: BigInt(6),
    name: 'Samsung Galaxy Buds2 Pro',
    brand: 'Samsung',
    category: 'Accessories',
    price: BigInt(17999),
    imageUrl: null,
    description: 'High-quality wireless earbuds with 360 audio',
  },
  {
    id: BigInt(7),
    name: 'Anker PowerCore 20K',
    brand: 'Anker',
    category: 'Accessories',
    price: BigInt(3999),
    imageUrl: null,
    description: 'High-capacity portable charger for all devices',
  },
  {
    id: BigInt(8),
    name: 'Spigen Ultra Hybrid Case',
    brand: 'Spigen',
    category: 'Accessories',
    price: BigInt(1499),
    imageUrl: null,
    description: 'Clear protective case with military-grade protection',
  },
  {
    id: BigInt(9),
    name: 'Xiaomi 13 Pro',
    brand: 'Xiaomi',
    category: 'Smartphones',
    price: BigInt(79999),
    imageUrl: null,
    description: 'Flagship with Leica camera system',
  },
  {
    id: BigInt(10),
    name: 'Belkin 3-in-1 Wireless Charger',
    brand: 'Belkin',
    category: 'Accessories',
    price: BigInt(8999),
    imageUrl: null,
    description: 'Charge phone, watch, and earbuds simultaneously',
  },
];

export const sampleServices = [
  {
    id: 1,
    title: 'Screen Repair & Replacement',
    description: 'Professional screen repair service for all major brands. We use high-quality parts and offer same-day service for most models. Get your device looking like new again.',
    icon: 'repair',
  },
  {
    id: 2,
    title: 'Device Unlocking',
    description: 'Unlock your phone to use with any carrier. Safe and reliable unlocking service for all major brands. Switch carriers without buying a new phone.',
    icon: 'unlock',
  },
  {
    id: 3,
    title: 'Battery Replacement',
    description: 'Is your battery draining fast? We replace batteries for all smartphone models with genuine or high-quality aftermarket batteries. Restore your device\'s battery life.',
    icon: 'battery',
  },
  {
    id: 4,
    title: 'Accessories & Protection',
    description: 'Wide selection of cases, screen protectors, chargers, and more. Protect your investment with quality accessories from trusted brands.',
    icon: 'accessories',
  },
  {
    id: 5,
    title: 'Trade-In Program',
    description: 'Get the best value for your old device. We accept all brands and conditions. Trade in your old phone and upgrade to the latest model with instant credit.',
    icon: 'trade',
  },
  {
    id: 6,
    title: 'Technical Support',
    description: 'Expert technical support for all your mobile needs. From setup assistance to troubleshooting, our team is here to help you get the most out of your device.',
    icon: 'support',
  },
];
